config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'articles/index'
    end
  end
  devise_for :admins
  root 'homes#index'

  resources :homes

  resources :categories

  namespace :admins do
    namespace :articles do
      post 'csv_upload'
    end

    resources :test_articles, only: :index

    resources :articles do
      resources :comments
    end
  end

  namespace :api do
    namespace :v1 do
      resources :articles, only: [] do
        resources :comments, only: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  enum status: { draft: 0, published: 1, archived: 2 }

  scope :long_title, ->(length = 15) { where('LENGTH(title) > ?', length) }
  scope :short_body, ->(length = 5) { where('LENGTH(body) < ?', length) }
  scope :search, ->(arg) { where('title LIKE ? or body LIKE ?', "%#{arg}%", "%#{arg}%") }

  has_one_attached :cover_image
  has_many_attached :images
  has_many :comments
  has_many :categories, through: :article_categories

  validates :title, :body, presence: true, uniqueness: true
  validates :title, length: { minimum: 3, maximum: 16 }
  validates :body, length: { minimum: 10 }
  # Other default validations

  validate :no_bad_words_in_title

  before_save :clean_data

  def no_bad_words_in_title
    errors.add(:title, 'cannot contains bad words') if title.include?('bad')
  end

  def clean_data
    self.title = title.upcase.squish
    self.body = body.humanize
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :category
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/admins/articles_controller.rb
module Admins
  class ArticlesController < ApplicationController
    before_action :authenticate_admin!

    def index
      @search = params[:search]

      @articles = Article.all
      @articles = @articles.search(@search) if @search.present?
      @articles = @articles.page(params[:page])
                           .order(updated_at: :desc).per(10)

      respond_to do |format|
        format.html
        format.csv { send_data generate_csv(@articles), file_name: 'articles.csv' }
      end
    end

    def new
      @article = Article.new
    end

    def show
      @article = Article.find(params[:id])
    end

    def create
      @article = Article.create(article_params)

      flash[:error] = @article.errors.full_messages if @article.invalid?

      redirect_to action: :index
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id])
      @article.update(article_params)
      redirect_to action: :index
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to action: :index
    end

    def csv_upload
      data = params[:csv_file].read.split("\n")
      data.each do |line|
        attr = line.split(',').map(&:strip)
        Article.create title: attr[0], body: attr[1]
      end
      redirect_to action: :index
    end

  private

    def generate_csv(articles)
      articles.map { |a| [a.title, a.body, a.created_at.to_date].join(',') }.join("\n")
    end

    def article_params
      params.require(:article).permit(:title, :body, :cover_image, images: [], category_ids: [])
    end
  end
end

app/controllers/admins/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]

  def index
    @search = params[:search]

    @categories = Category.all
    @categories = @categories.search(@search) if @search.present?
    @categories = @categories.page(params[:page])
                             .order(updated_at: :desc).per(10)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(@categories), file_name: 'articles.csv' }
    end

    def new
      @category = Category.new
    end

    def show
      @category = Category.find(params[:id])
    end

    def create
      @category = Category.create(product_params)

      flash[:error] = @category.errors.full_messages if @category.invalid?

      redirect_to action: :index
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      @category.update(product_params)
      redirect_to action: :index
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      redirect_to action: :index
    end

    def csv_upload
      data = params[:csv_file].read.split("\n")
      data.each do |line|
        attr = line.split(',').map(&:strip)
        Article.create title: attr[0], body: attr[1]
      end
      redirect_to action: :index
    end

    private

    def generate_csv(articles)
      articles.map { |a| [a.title, a.body, a.created_at.to_date].join(',') }.join("\n")
    end

    def product_params
      params.require(:category).permit(:name, :description, :stock)
    end
  end
end

app/controllers/admins/comments_controller.rb
module Admins
  class CommentsController < ApplicationController
    def create
      @article = Article.find params[:article_id]
      @article.comments.create(comment_params)
      redirect_to admins_article_path(@article)
    end

    private

    def comment_params
      params.require(:comment).permit(:author, :text)
    end
  end
end

app/controllers/admins/test_articles_controller.rb
module Admins
  class TestArticlesController < ApplicationController
    def index
      @search = params[:search]
      @articles = Article.all
      if @search.present?
        @articles = @articles.where('title LIKE ? or body LIKE ?', "%#{@search}", "%#{@search}").page(@search).per(5)
      end
      @articles = @articles.page(params[:page]).per(10)
    end
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    @comments = Article.find(params[:article_id]).comments
    render json: @comments
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @articles = Article.all.page(params[:page]).per(25)
  end
end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/test_articles_helper.rb
module TestArticlesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/admins/articles/_form.slim
= form_with model: [:admin, @articles] do |f|
  div Cover Image
  div = f.file_field :cover_image
  div Title
  div = f.text_field :title, placeholder: 'Title'
  div Body
  div = f.text_area :body, placeholder: 'Write content here'
  div Images
  div = f.file_field :images, multiple: true
  / div Category
  / div = f.collection_check_boxes :category_ids
  div = f.submit 'Submit Article'

app/views/admins/articles/edit.slim
h1 Edit new article

div
  = link_to admins_articles_path do
    =button_tag 'Back', class: 'btn btn-primary'
br
  =render 'form', article: @article

app/views/admins/articles/index.slim
.row
  .col-6
    h1 This is articles list
  .col-6
    .float-right
      div = current_admin.email
      span = "#{current_admin.firstname} #{current_admin.lastname}"
      span.ml-3 = link_to 'Logout', destroy_admin_session_path, method: :delete

.row
  .col
    = form_tag admins_articles_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something', class: 'form-control'
  .col-2
    = link_to admins_articles_path(format: :csv) do
      = button_tag 'Download CSV', class: 'btn btn-secondary float-right'
.row.mt-2
  .col-12
    table.table.table-hover
      thead.thead-dark
        tr
          th ID
          th Cover
          th Status
          th Title
          th Body
          th Categories
          th No. Comments
          th Images
          th Created at
          th Updated at
          th Action
      tbody
        - @articles.each do |a|
          tr
            td = a.id
            td = a.status
            td
              - if a.cover_image.attached?
                = image_tag a.cover_image, width: '64px'
            td.font-weight-bold = a.title.first(16)
            td = a.body
            / td = a.categories&.map(&:name)&.join(',').presence || 'NA'
            td = a.comments.count
            td
              - a.images.each do |image|
                = image_tag image, width: '32px'
            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
            td
              span
              = link_to admins_article_path(a) do
                i.fas.fa-eye
              span.ml-3
              = link_to edit_admins_article_path(a) do
                i.fas.fa-pen
              span.ml-3
              = link_to admins_article_path(a), method: :delete do
                i.fas.fa-trash

.row
  .col-6
    = paginate @articles
  .col-6
    .float-right
      = link_to new_admins_article_path do
        = button_tag 'Add new Article', class: 'btn btn-primary'

div
  hr

.row
  .col
    = form_tag admins_articles_csv_upload_path, multipart: true do
      div = file_field_tag :csv_file
      div = submit_tag :upload

app/views/admins/articles/new.slim
h1 Add new article

div
  = link_to admins_articles_path do
    =button_tag 'Back', class: 'btn btn-primary'
br
  =render 'form', article: @article

app/views/admins/articles/show.slim
h1 = @article.title
hr
div = @article.body
div = link_to 'Back', admins_articles_path
hr
  h2 Comments Section
  div
    - @article.comments.each do |comment|
      div
        = "#{comment.author} Wrote : #{comment.text}"
hr
  h2 Add new Comment Section
  =form_with model: [@article, @article.comments.build] do |f|
    div = f.text_field :author, placeholder: 'Author'
    div = f.text_area :text, placeholder: 'Write text here'
    div = f.submit 'Submit Comment'

app/views/admins/categories/_form.slim
= form_with model: @category do |f|
  div = f.text_field :name, placeholder: 'Name'
  div = f.text_area :description, placeholder: 'Write content here'
  div = f.submit 'Submit Category'

app/views/admins/categories/edit.slim
h1 Edit new category

div
  = link_to categories_path do
    = button_tag 'Back', class: 'btn btn-primary'
br
  = render 'form', category: @category

app/views/admins/categories/index.slim
.row
  .col-6
    h1 This is categories list
  .col-6
    - if current_admin
      div = current_admin.email
      div = link_to 'Logout', destroy_admin_session_path, method: :delete
    - else
      div = link_to 'Login', new_admin_session_path

.row
  .col
    = form_tag categories_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'type something here', class: 'form-control'

.row.mt-2
  .col-12
    = link_to products_path do
      = button_tag 'Product', class: 'btn btn-primary'
    table.table.table-hover
      thead.thead-dark
        tr
          th ID
          th Name
          th Description
          th Created at
          th Updated at
          th Action
      tbody
        - @categories.each do |a|
          tr
            td = a.id
            td = a.name
            td = a.description
            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
            td
              span
              = link_to category_path(a) do
                i.fas.fa-eye
              - if current_admin
                span.ml-3
                  = link_to edit_category_path(a) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to category_path(a), method: :delete do
                    i.fas.fa-trash

.row
  .col-6
    = paginate @categories
  - if current_admin
    .col-6
      .float-right
        = link_to new_category_path do
          = button_tag 'Add new Category', class: 'btn btn-primary'

app/views/admins/categories/new.slim
h1 Add new category

div
  = link_to categories_path do
    = button_tag 'Back', class: 'btn btn-primary'
br
  = render 'form', category: @category

app/views/admins/categories/show.slim
h1 = @category.name
hr
div = @category.description
div
  = link_to categories_path do
    = button_tag 'Back', class: 'btn btn-primary'
hr

app/views/admins/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/articles/_form.slim
= form_with model: @article do |f|
  div Cover Image
  div = f.file_field :cover_image
  div Title
  div = f.text_field :title, placeholder: 'Title'
  div Body
  div = f.text_area :body, placeholder: 'Write content here'
  div Images
  div = f.file_field :images, multiple: true
  / div Category
  / div = f.collection_check_boxes :category_ids
  div = f.submit 'Submit Article'

app/views/articles/edit.slim
h1 Edit new article

div
  = link_to articles_path do
    =button_tag 'Back', class: 'btn btn-primary'
br
  =render 'form', article: @article

app/views/articles/index.slim
.row
  .col-6
    h1 This is articles list
  .col-6
    .float-right
      div = current_admin.email
      span = "#{current_admin.firstname} #{current_admin.lastname}"
      span.ml-3 = link_to 'Logout', destroy_admin_session_path, method: :delete

.row
  .col
    = form_tag articles_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something', class: 'form-control'
  .col-2
    = link_to articles_path(format: :csv) do
      = button_tag 'Download CSV', class: 'btn btn-secondary float-right'
.row.mt-2
  .col-12
    table.table.table-hover
      thead.thead-dark
        tr
          th ID
          th Cover
          th Status
          th Title
          th Body
          th Categories
          th No. Comments
          th Images
          th Created at
          th Updated at
          th Action
      tbody
        - @articles.each do |a|
          tr
            td = a.id
            td = a.status
            td
              - if a.cover_image.attached?
                = image_tag a.cover_image, width: '64px'
            td.font-weight-bold = a.title.first(16)
            td = a.body
            td = a.categories&.map(&:name)&.join(',').presence || 'NA'
            td = a.comments.count
            td
              - a.images.each do |image|
                = image_tag image, width: '32px'
            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
            td
              span
              = link_to article_path(a) do
                i.fas.fa-eye
              span.ml-3
              = link_to edit_article_path(a) do
                i.fas.fa-pen
              span.ml-3
              = link_to article_path(a), method: :delete do
                i.fas.fa-trash

.row
  .col-6
    = paginate @articles
  .col-6
    .float-right
      = link_to new_article_path do
        = button_tag 'Add new Article', class: 'btn btn-primary'

div
  hr

.row
  .col
    = form_tag articles_csv_upload_path, multipart: true do
      div = file_field_tag :csv_file
      div = submit_tag :upload

app/views/articles/new.slim
h1 Add new article

div
  = link_to articles_path do
    =button_tag 'Back', class: 'btn btn-primary'
br
  =render 'form', article: @article

app/views/articles/show.slim
h1 = @article.title
hr
div = @article.body
div = link_to 'Back', articles_path
hr
  h2 Comments Section
  div
    - @article.comments.each do |comment|
      div
        = "#{comment.author} Wrote : #{comment.text}"
hr
  h2 Add new Comment Section
  =form_with model: [@article, @article.comments.build] do |f|
    div = f.text_field :author, placeholder: 'Author'
    div = f.text_area :text, placeholder: 'Write text here'
    div = f.submit 'Submit Comment'

app/views/homes/index.html.slim
.row
  .col
    span.float-right
      = link_to 'Go to admin section', admins_articles_path

h1 Welcome to our Blog Site

- @articles.each do |article|
  .row.mt-2
    .col
      .card.card-body
        .row
          .col-3
            div Image
            -if article.cover_image.attached?
              = image_tag article.cover_image, width: '100%'
          .col-9
            .row
              .col
                h2 = article.title
            .row
              .col
                = article.body
            .row.mt-3
              .col
                = button_tag 'Load Comments', class: 'btn btn-outline-secondary btn-comment', article: article.id
            .row.mt-1
              .col
                div id="comments-#{article.id}"

app/views/test_articles/index.slim
.row
  .col-6
    h1 This is articles list

.row.mt-2
  .col-12
    table.table.table-hover
      thead.thead-dark
        tr
          th ID
          th Title
          th Body
          th Number of comments
          th Created at
          th Updated at
          th Action
      tbody
        - @articles.each do |a|
          tr
            td = a.id
            td = a.title
            td = a.body
            td = a.comments.count
            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
            td
              span
              = link_to article_path(a) do
                i.fas.fa-eye
              span.ml-3
              = link_to edit_article_path(a) do
                i.fas.fa-pen
              span.ml-3
              = link_to article_path(a), method: :delete do
                i.fas.fa-trash

.row
  .col-12
    .float-right
      = link_to new_article_path do
        = button_tag 'Add new Article', class: 'btn btn-primary'